### ISSUE TITLE
publish module to npm or make some dependencies to be with ~ and not ^

### ISSUE THREAD

**Issue by borisirota** [75lb/boil#3]
Hey,

I'm using jsdoc-to-markdown and after the last update of the handlebars modules there is an exception:
```
/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/boil-js/lib/boil.js:17
require("handlebars-comparison")(handlebars);
                                ^
TypeError: object is not a function
```

Please prefix the handlebars-comparison and handlebars-string dependencies with ~ and not ^ in version `0.2.9` because the current update break things.

Or, publish the new version (0.4.0) to npm and update the boil-js dependency in the dmd module to be `"boil-js": "~0.4.0"`.

Thanks !

**Comment by 75lb** [comment]
confirmed.. on the case.. tsk, so sloppy!

**Comment by 75lb** [comment]
it should be fixed now, you will need to re-install: 
```
$ npm i -g jsdoc-to-markdown
```
i broke this last night, tired, doing a batch of mundane, repetitive tasks - sorry!

**Comment by borisirota** [comment]
Thanks ! :)

**Comment by 75lb** [comment]
thanks for the report.. i'm just putting the finishing touches to the new release..

**Comment by borisirota** [comment]
Sounds good !
BTW, I made the [jsdoc2md-anchors](https://github.com/borisirota/jsdoc2md-anchors) utility in order to adjust the anchors to be compatible with Github and Bitbucket.
In my opinion, it can be useful if it comes out of the box so think about it :)

**Comment by 75lb** [comment]
cool.. yeah, i know about the issues with Bitbucket (i will fix soon) but the anchors should work with Github.. 

It’s actually much easier to customise the output than the solution you arrived at.. it’s my fault - it’s not well documented at all!

The new version will have a simple plug-in mechanism, i’ll writing up the docs as we speak.. 

will get back to you when it’s live..

**Comment by borisirota** [comment]
Awesome ! I'm using `jsdoc-to-markdown` everywhere :)

If you can address the custom replacements I made [here](https://github.com/borisirota/jsdoc2md-anchors/blob/master/bin/jsdoc2md-anchors.js#L18) to the anchor's output it will be great. I guess I should have posted an issue to the anchor project in order to solve this. I'll do it now :)

Do the plug-in mechanism will work through the command line ?

**Comment by borisirota** [comment]
FYI, if you're using the anchor module so I posted an issue ([20](https://github.com/thlorenz/anchor-markdown-header/issues/20)) and made a pull request to address the custom replacements I made.

**Comment by 75lb** [comment]
when i get a moment i will send you an example of how to get the behaviour you want using @next
